### PR TITLE
New game: Super Monkey Ball

### PR DESCRIPTION
**Pull request by spicynun**
Adding the first Super Monkey Ball to HintMachine.

### CODE REVIEW

**Comment by Dinopony** [comment]
Connector looks fine, needs to be tested.
I can't do it right now, but might a bit later: if anyone wants to test it in the meantime, feel free.

**Comment by Dinopony** [comment]
Nothing to say from a technical standpoint, the connector works perfectly 👍 
About the balance, I did a quick run (about 6 min) of the beginner levels while being average in terms of skill, and I've got about 6 hints.

image

I don't know if there are factors that I don't know, but it seems to me that the quests are significantly too quick to be done.
A few remarks / suggestions regarding quests:
- Completed levels favors playing beginner levels by **a lot**. Maybe it's not adapted to be a good quest metric?
- Bananas are super cool, but there are levels where they could become easily death-abusable in levels where big chunks of banans are available early in the level. Maybe only validate the banana count when completing a level?
- I don't know this version very well, but I saw the game awards you "Play Points" when completing levels. This might be a super bad idea, but if it rewards more play points for harder levels, it might be a better metric than "Completed Levels"?

That's a super cool game addition nonetheless 😄

**Comment by spicynun** [comment]
Yeah I was worried about that with the stage clears. I originally had it at 5 for both Monkey Ball 1 and 2. Maybe I'll set it back to 5 for both then if someone is stuck on a level in a later difficulty they could still work towards the banana goal since they are still counted between deaths? But I see what you mean about it being death-abusable. I'll definitely look into play points maybe as a replacement though if the stage clears still feel too quick at 5 and maybe also look into counting bananas only when completing a level. Thanks for the feedback!

**Comment by spicynun** [comment]
That was a great idea on the play points! The higher floors and difficulties do award more which gives more of a reason to play the higher difficulties now. Might need to tweak the goal for it a bit. I should also change the stage clear goal to play points in Super Monkey Ball 2 as well. I'll be sure to make it so the bananas can't be death farmed soon.

**Comment by Dinopony** [comment]
Great work :)
Do you think the game is okay to be merged and you'll add the banana check later on, or are you gonna do it early enough so it would be a waste to merge it now?

**Comment by spicynun** [comment]
Yeah I think it's okay to be merged! I'll look into the banana check a bit later, I'm not too worried since death farming would just make them game over anyways. But it is something I still want to look into.

**Pull request merged**
