### PR TITLE
Post Game Update Fix: TMNT Shredder's Revenge

### PR DESCRIPTION
**Pull request by nbrochu**
Only needed an executable hash update. Pointer is still good.

### CODE REVIEW

**Comment by Dinopony** [comment]
The fix targets `dev`, but it would be more convenient for it to target `beta` (only having the hash modification).

This will prevent having to merge from dev to beta (which is kind of inconvenient since we don't want some feature from dev to go to beta until 1.2.0 is released).

**Comment by nbrochu** [comment]
I am not really aware of the branch setup and git flow we want to use. Beta will be next RCs and eventual releases? Dev is targeting next version?

**Comment by Dinopony** [comment]
Exactly!
That's my bad on not documenting it properly. I'll take notes on adding this to docs.

**Comment by nbrochu** [comment]
Did interactive rebase to only pick the TMNT commit and pointed the PR to beta

**Pull request merged**
