### PR TITLE
New Game: Pinball FX3

### PR DESCRIPTION
**Pull request by nbrochu**
Works on the F2P table rotation and any base game / DLC tables (100 of them!)

image
image

### CODE REVIEW

**Comment by CalDrac** [comment]
The idea is cool, technically the PR is OK, but functionnaly, I think there is some more work.

Tables have scoring systems varying too much one from another (i.e Attack from Mars easily goes to hundreds of millions / billions if you're middle skilled)

Second question : Ain't there a security program included ? Because there are leaderboards and online duels

**Comment by nbrochu** [comment]
I understand your point. I know of the variance, but I found 5M to be a decent sweet spot. I don't really intend to discover how to identify which table is played and then have 1 balanced quest per table when there are 100 of them though, especially when so little people own multiple pieces of DLC. I suggest we start like this and adjust based on feedback.

No real security or anticheat per se. There is a struct for all the competitive stats and you can read the scores just fine. I'm guessing they track events while playing and if the score doesn't match what happens when you replay events they invalidate / ban based on that

**Comment by nbrochu** [comment]
I will start looking into how to identify which table is being played nonetheless

**Comment by nbrochu** [comment]
Let's leave this open, I didn't think the problem was THAT bad with classic tables like Attack on Mars

**Comment by nbrochu** [comment]
Alright, I went ahead and did exactly what I said I wouldn't do: Have a target score for each individual table, identify the one we are playing on and apply a multiplier to the generated score while playing to normalize score acquisition. 

Stupid amount of manual work, but the final result is much better for it. I individually tested all 100 tables (😅). The only known issue is the UI stuff I discussed in #general-dev.
image

**Comment by Dinopony** [comment]
Since this is gonna need a UI rework, I'm OK with merging it right now but I'd like to postpone its release for 1.3.0.
This will allow releasing the 1.2.0 early and let more time to work on the UI stuff to release this in a clean manner.

**Comment by nbrochu** [comment]
Works for me. Can still be played in dev build ;)

**Comment by Dinopony** [comment]
This has been merged in 8244b13, but I did it manually so Github wasn't notified.

**Pull request closed without merging**
